/** Rebuild public HTML from existing reports. No network or new dependencies. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import vm from 'node:vm';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = path => readFileSync(resolve(root, path), 'utf8');
const write = (path, content) => {
  mkdirSync(dirname(resolve(root, path)), { recursive: true });
  writeFileSync(resolve(root, path), content, 'utf8');
};
const { Marked } = createRequire(import.meta.url)('../hk-top100-reports/vendor/marked.min.js');
const source = JSON.parse(read('hk-top100-reports/data/companies.json'));
const companies = [...source.companies].sort((a, b) => a.rank - b.rank);
const content = vm.runInNewContext(`${read('js/content.js')}\nSITE_CONTENT;`);
const origin = 'https://ai10xpro.com';
const brand = 'Edward LEE｜發掘十倍股';
const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
const plain = text => text.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1').replace(/[*_`#]/g, '').trim();
const companyUrl = c => `/research/hk/${c.symbol}/`;
const reports = new Map(companies.map(c => [c.symbol, read(`hk-top100-reports/reports/${c.file}`)]));
const reportDate = c => {
  // Source filenames carry the report version date; body dates may be IPO dates.
  const [, year, month, day] = c.file.match(/_(\d{4})(\d{2})(\d{2})\.md$/);
  return `${year}-${month}-${day}`;
};
const sections = c => [...reports.get(c.symbol).matchAll(/^## (.+)$/gm)].map(match => plain(match[1]));
const desc = c => `${c.shortName}（${c.code}）免費公司研究，涵蓋${sections(c).slice(0, 3).join('、')}。報告日期 ${reportDate(c)}，附完整分析及資料來源說明。`;
const featured = ['00700', '00005', '09988'].map(symbol => companies.find(c => c.symbol === symbol));
const insight = c => {
  const text = reports.get(c.symbol).match(/^\*\*核心解讀\*\*[：:]\s*(.+)$/m)?.[1];
  return text ? plain(text) : sections(c).slice(0, 3).join(' · ');
};

const header = `<a class="skip-link" href="#main">跳到主要內容</a>
<header class="masthead"><div class="shell">
<a class="brand" href="/"><span class="brand-mark">10×</span><span>EDWARD LEE<small>發掘十倍股</small></span></a>
<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">選單</button>
<nav class="main-nav" id="main-nav" aria-label="主要導覽"><a href="/research/">查股票</a><a href="/#updates">研究更新</a><a href="/free/">免費工具</a><a href="/about/">關於 Edward</a><a class="login-link" href="/member/">會員登入 ↗</a></nav>
</div></header>`;
const footer = `<footer class="site-footer" id="social"><div class="shell"><div class="footer-top"><a class="brand" href="/">EDWARD LEE <small>發掘十倍股</small></a><nav class="footer-links" aria-label="社群及延伸閱讀"><a href="/archive/">文章摘要庫</a><a href="https://www.facebook.com/28investment" target="_blank" rel="noopener noreferrer">Facebook ↗</a><a href="https://www.threads.net/@edwardleeten" target="_blank" rel="noopener noreferrer">Threads ↗</a><a href="https://www.instagram.com/edwardleeten/" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://twitter.com/EdwardLee239412" target="_blank" rel="noopener noreferrer">X ↗</a><a href="https://discord.gg/Y8wk7DCWPR" target="_blank" rel="noopener noreferrer">Discord ↗</a></nav></div><p>研究內容只供參考及教育用途，唔構成投資建議。歷史報告、股價及估值只反映列明日期，過去表現唔保證未來回報。</p><p>© Edward LEE · 發掘十倍股</p></div></footer>`;
const newsletter = `<div class="newsletter"><p class="eyebrow">STAY IN THE LOOP</p><h2>有值得跟進嘅研究，收到通知。</h2><p>登記電郵，接收公開研究同資料庫更新。只用作研究更新聯絡。</p><form class="newsletter-form" action="/api/subscribe" method="post"><label class="sr-only" for="newsletter-email">接收研究更新嘅電郵地址</label><input id="newsletter-email" name="email" type="email" placeholder="你嘅電郵地址" autocomplete="email" required maxlength="254"><button class="button" type="submit" disabled>登記研究更新 ↗</button><p class="form-message" role="status">請啟用 JavaScript 以登記電郵；亦可以透過下方社群連結跟進更新。</p></form></div>`;
function page(title, description, path, body, schema = null, searchData = false) {
  const url = origin + path;
  return `<!doctype html>
<!-- Generated by scripts/build_research_pages.mjs; edit its source or templates. -->
<html lang="zh-Hant-HK"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}｜${brand}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index, follow"><link rel="canonical" href="${url}">
<meta property="og:type" content="${schema?.['@type'] === 'Article' ? 'article' : 'website'}"><meta property="og:locale" content="zh_HK"><meta property="og:site_name" content="${brand}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}">
<meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}">
${path === '/' ? '<meta name="google-site-verification" content="A-75Wb1cMKKp4CCM3zgAugcVho9vZa-YihIezik4p7Y"><meta property="og:image" content="https://ai10xpro.com/assets/hero-bg.jpg"><meta name="twitter:image" content="https://ai10xpro.com/assets/hero-bg.jpg">' : ''}
<link rel="icon" href="/assets/research-mark.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@500;600;700;800&family=Noto+Sans+TC:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/research.css?v=20260908">
<noscript><style>.main-nav{display:flex!important}.menu-toggle{display:none!important}</style></noscript>
${schema ? `<script type="application/ld+json">${json({ '@context': 'https://schema.org', ...schema })}</script>` : ''}
${searchData ? '<script src="/js/research-companies.js?v=20260908" defer></script>' : ''}<script src="/js/research.js?v=20260908" defer></script>
</head><body class="research-site">${header}<main id="main">${body}</main>${footer}</body></html>\n`;
}
function card(c, summary = null) {
  const excerpt = summary || insight(c);
  return `<article class="research-card" data-symbol="${c.symbol}"><div class="card-meta"><span class="tag">免費全文</span><time datetime="${reportDate(c)}">${reportDate(c)}</time></div><h3><a href="${companyUrl(c)}" data-track="report_click">${esc(c.shortName)}</a></h3><span class="company-code">${c.code} · ${esc(c.industry)}</span><p>${esc(excerpt.length > 100 ? excerpt.slice(0, 100) + '…' : excerpt)}</p><a class="text-link" href="${companyUrl(c)}" data-track="report_click">閱讀公司研究 ↗</a></article>`;
}
const share = `<div class="article-actions"><button class="button" type="button" data-share="native" hidden>分享研究 ↗</button><button class="button secondary" type="button" data-share="copy" hidden>複製連結</button><a class="button secondary" href="#newsletter">接收研究更新 ↓</a></div><p id="share-message" class="form-message" role="status"></p>`;

// Raw HTML is escaped; only safe protocols survive Markdown link rendering.
function renderReport(markdown) {
  let heading = 0;
  const toc = [];
  const renderer = {
    html({ text }) { return esc(text); },
    heading({ tokens, depth, text }) {
      const level = Math.max(2, depth);
      const id = `section-${heading++}`;
      if (depth === 2) toc.push({ id, text: plain(text) });
      return `<h${level} id="${id}">${this.parser.parseInline(tokens)}</h${level}>\n`;
    },
    link({ href, tokens }) {
      const text = this.parser.parseInline(tokens);
      if (!/^(https?:\/\/|#)/i.test(href)) return text;
      return `<a href="${esc(href)}"${href.startsWith('#') ? '' : ' target="_blank" rel="noopener noreferrer"'}>${text}</a>`;
    },
    image({ text }) { return esc(text); },
  };
  const parser = new Marked({ gfm: true, breaks: true, renderer });
  const body = parser.parse(markdown.replace(/^# .*\r?\n/, ''))
    .replace(/<table>/g, '<div class="table-scroll" role="region" aria-label="研究數據表，可橫向捲動" tabindex="0"><table>')
    .replace(/<\/table>/g, '</table></div>');
  return { body, toc };
}

for (const c of companies) {
  const { body, toc } = renderReport(reports.get(c.symbol));
  const related = companies.filter(other => other.symbol !== c.symbol && other.industry === c.industry).slice(0, 3);
  const html = `<div class="shell"><nav class="breadcrumbs" aria-label="麵包屑"><a href="/">首頁</a> / <a href="/research/">公司研究</a> / ${esc(c.shortName)}</nav><header class="article-heading"><p class="eyebrow">HONG KONG / ${c.code}</p><h1>${esc(c.shortName)}<br>公司業績與研究</h1><div class="card-meta"><span class="tag">免費全文</span><span>${esc(c.industry)}</span><span>報告日期 <time datetime="${reportDate(c)}">${reportDate(c)}</time></span></div><p class="note">收錄自 Edward LEE 研究庫。以下保留原報告內容及來源說明；資料、股價及估值截至原文列明日期。</p>${share}</header><div class="reading-layout"><details class="toc" open><summary>報告目錄</summary><nav aria-label="報告章節">${toc.map(h => `<a href="#${h.id}">${esc(h.text)}</a>`).join('')}</nav><a href="/hk-top100-reports/reports/${encodeURIComponent(c.file)}">查看原始報告 ↗</a></details><article class="report-body" id="report" data-symbol="${c.symbol}">${body}</article></div><section class="section"><div class="section-heading"><div><p class="eyebrow">KEEP READING</p><h2>繼續研究${esc(c.industry)}</h2></div><a class="text-link" href="/research/">全部公司 ↗</a></div><div class="cards">${related.map(c => card(c)).join('')}</div><p><a class="text-link" href="/free/stocks/hk">比較港股業績 ↗</a> · <a class="text-link" href="/free/themes">睇主題強弱 ↗</a></p></section><section class="section" id="newsletter">${newsletter}</section></div>`;
  write(`research/hk/${c.symbol}/index.html`, page(`${c.shortName} ${c.code} 公司業績與研究`, desc(c), companyUrl(c), html, {
    '@type': 'Article', headline: `${c.shortName}（${c.code}）公司研究`, datePublished: reportDate(c),
    author: { '@type': 'Organization', name: 'Edward LEE 研究庫', url: origin + '/about/' },
    publisher: { '@type': 'Organization', name: brand, url: origin }, mainEntityOfPage: origin + companyUrl(c),
    description: desc(c), inLanguage: 'zh-Hant-HK',
  }));
}

const directory = `<div class="shell"><header class="page-intro"><p class="eyebrow">THE RESEARCH LIBRARY</p><h1>由你關心嘅公司開始。</h1><p>${companies.length} 間港股公司研究，免費閱讀全文。今期資料版本 ${esc(source.as_of)}；個別報告日期及數據口徑見原文。</p></header><div class="filter-bar"><label class="sr-only" for="directory-query">搜尋公司</label><input id="directory-query" type="search" placeholder="搜尋公司、代號或英文名，例如 700、Tencent"><label class="sr-only" for="directory-industry">按行業篩選</label><select id="directory-industry"><option value="">全部行業</option>${source.industries.map(i => `<option value="${esc(i)}">${esc(i)}</option>`).join('')}</select></div><p class="directory-count" id="directory-count" role="status">${companies.length} 間公司 · 按原資料市值排名排列</p><noscript><p>以下已列出全部公司，可以直接開啟報告；搜尋同篩選需要 JavaScript。</p></noscript><p id="directory-empty" hidden>未搵到符合條件嘅公司，試下其他名稱或全部行業。</p><div class="cards" id="directory">${companies.map(c => card(c)).join('')}</div><section class="section" id="newsletter">${newsletter}</section></div>`;
write('research/index.html', page('港股公司研究與免費業績報告', '按公司名稱、股份代號或行業搜尋港股公司研究，免費閱讀完整報告、查看資料日期及相关公司。', '/research/', directory, null, true));

const latest = [...companies].sort((a, b) => reportDate(b).localeCompare(reportDate(a)) || a.rank - b.rank).slice(0, 3);
const financialRows = ['收入', '毛利', '經營盈利'].map(label => {
  const row = reports.get('00700').split('\n').find(line => line.startsWith(`| ${label} |`));
  if (!row) throw new Error(`Missing source row: ${label}`);
  return `<tr><th scope="row">${label}</th><td>${esc(plain(row.split('|').at(-2)))}</td></tr>`;
}).join('');
const financialPreview = `<table class="data-preview"><caption>騰訊研究節錄 · 2026 上半年同比 · 報告日 ${reportDate(featured[0])}</caption><thead><tr><th scope="col">指標</th><th scope="col">同比變化</th></tr></thead><tbody>${financialRows}</tbody></table>`;
const values = { COMPANY_COUNT: companies.length, AS_OF: source.as_of, FEATURE_DATE: reportDate(featured[0]), FINANCIAL_PREVIEW: financialPreview,
  FEATURED_CARDS: featured.map(c => card(c)).join(''), LATEST_CARDS: latest.map(c => card(c)).join(''), NEWSLETTER: newsletter };
const homepage = read('scripts/templates/research-home.html').replace(/\{\{(\w+)\}\}/g, (_, key) => values[key]);
write('index.html', page('港股業績、公司研究與免費投資工具', '查閱港股公司研究、比較業績、追蹤主題強弱。Edward LEE 發掘十倍股提供免費完整報告、研究更新及會員工具。', '/', homepage, {
  '@type': 'WebSite', name: brand, url: origin, inLanguage: 'zh-Hant-HK',
}, true));

const tools = [
  ['查一間公司', '港股公司研究', `${companies.length} 間公司嘅完整研究，涵蓋公司概況、業績、估值同風險。資料版本 ${source.as_of}。`, '/research/', '免費全文'],
  ['比较業績', '港股業績資料庫', '比較收入、毛利增長、行業分類同相對恒指表現。收錄 2025 年 12 月年結資料。', '/free/stocks/hk', '歷史業績 / H2 2025'],
  ['追蹤一個主題', '主題強弱監測', '由市場主題排名，查看主題內領先或落後嘅公司。數據日期以工具內標示為準。', '/free/themes', '市場監測'],
  ['搵相關公司', '港股關鍵字資料庫', '由產品、服務同業務關鍵字搵公司，或者由公司反查相關主題。', '/free/keywords/hk', '業務關鍵字'],
  ['重看當時判斷', '港股中期業績前景庫', '查看 2026 年 8 月 20 日公開快照，包括財務主線、催化劑、風險同展望。', '/free/outlook-2026-archive', '歷史快照 / 2026-08-20'],
  ['研究美股龍頭', 'S&P 500 公司研究', '現有 18 間美股公司報告，包含公司背景、業績、催化劑同風險。資料日期見各份報告。', '/free/sp500-top20', '美股 / 免費報告'],
];
write('free-tools.html', page('免費投資研究工具', '按研究問題揀工具：查公司、比較港股業績、追蹤市場主題、搜尋業務關鍵字，全部免登入。', '/free/', `<div class="shell"><header class="page-intro"><p class="eyebrow">OPEN RESEARCH</p><h1>帶住問題，揀一個工具。</h1><p>六個免費研究入口，毋須登入。每個工具嘅資料期間各有不同，使用前留意日期。</p></header><div class="tools-grid">${tools.map((t, i) => `<article class="tool-card"><span class="tool-number">0${i + 1} / ${t[0]}</span><h2>${t[1]}</h2><span class="tag">${t[4]}</span><p>${t[2]}</p><a class="text-link" href="${t[3]}" data-track="tool_open">開啟工具 ↗</a></article>`).join('')}</div><section class="section"><h2>延伸閱讀與交流</h2><a class="text-link" href="/archive/">歷年文章摘要 ↗</a> · <a class="text-link" href="/#community">免費 Discord 社群 ↗</a></section><section class="section" id="newsletter">${newsletter}</section></div>`));

write('about.html', page('關於 Edward 與研究方法', '由 2012 年起公開記錄研究，了解 Edward LEE 嘅背景，以及業績、行業趨勢、資金與情緒三個研究方向。', '/about/', `<div class="shell"><header class="page-intro"><p class="eyebrow">ABOUT THE RESEARCH</p><h1>我係 Edward。<br>研究，係持續驗證判斷。</h1></header><article class="prose">${content.story.journey.map(p => `<p>${esc(p)}</p>`).join('')}<h2>我點樣睇一間公司</h2>${content.story.pillars.items.map(p => `<h3>${esc(p.label)}</h3><p>${esc(p.desc)}</p>`).join('')}<p>${esc(content.story.aiNote)}</p><h2>閱讀研究之前</h2><p>每份報告嘅資料範圍、來源、推算同日期，以原文說明為準。網站保留原報告內容，亦會有历史分析；唔應將歷史股價、估值或個別案例當成即時資訊。</p><p>AI 可以協助整理同覆蓋資料，最終仍然需要核對來源同判斷。個別分析可能有遺漏或判斷失準，可以透過公開社群討論。</p><a class="button" href="/research/">先睇一份完整報告 ↗</a><p><a href="https://www.facebook.com/28investment" target="_blank" rel="noopener noreferrer">Facebook 公開紀錄 ↗</a> · <a href="/archive/">歷年文章摘要 ↗</a></p></article><section class="section" id="newsletter">${newsletter}</section></div>`, { '@type': 'AboutPage', name: '關於 Edward LEE', url: origin + '/about/' }));

write('research/briefing/index.html', page(`${source.as_of} 公司研究選讀`, '由騰訊、滙豐及阿里巴巴研究開始，查阅業績與公司分析，分享完整研究連結。', '/research/briefing/', `<div class="shell"><header class="page-intro"><p class="eyebrow">RESEARCH SELECTION / ${esc(source.as_of)}</p><h1>三間公司，三個研究起點。</h1><p>今期選讀來自現有免費公司報告。由最新業績、業務結構同風險出發，完整資料及分析日期見原文。</p>${share}</header><div class="cards">${featured.map(c => card(c)).join('')}</div><section class="section prose"><h2>點樣用呢份選讀？</h2><p>先揀一間你關心嘅公司，讀業績拆解，再對照原文數據來源同風險章節。想延伸研究，可以睇同業公司，或者使用免費業績比較工具。</p><a class="text-link" href="/free/stocks/hk">比較港股業績 ↗</a></section><section class="section" id="newsletter">${newsletter}</section></div>`));

write('js/research-companies.js', `// Generated from the public company directory.\nwindow.RESEARCH_COMPANIES = ${json(companies.map(({ symbol, code, shortName, name_en, industry }) => ({ symbol, code, shortName, name_en, industry })))};\n`);
write('worker/research-symbols.js', `// Generated public research routes.\nexport const RESEARCH_SYMBOLS = new Set(${json(companies.map(c => c.symbol))});\n`);
write('sitemap-research.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${companies.map(c => `  <url><loc>${origin}${companyUrl(c)}</loc></url>`).join('\n')}\n</urlset>\n`);

// Keep the homepage's existing archive search/filter/pagination on its own route.
const archive = JSON.parse(read('web_data.json'));
const posts = [...archive.posts].sort((a, b) => b.date.localeCompare(a.date));
const years = [...new Set(posts.map(p => p.date.slice(0, 4)))].sort().reverse();
const archiveCards = posts.map(post => {
  const stockText = [...(post.hk || []), ...(post.us || [])].map(s => `${s.c} ${s.n || ''}`).join(' · ');
  return `<article class="research-card" data-archive-search="${esc(`${post.title} ${stockText} ${post.preview}`.toLowerCase())}" data-date="${esc(post.date)}" data-categories="${esc(post.cats.join(' '))}"><div class="card-meta"><span class="tag">公開摘要</span><time datetime="${esc(post.date)}">${esc(post.date)}</time></div><h2><a href="/archive/${esc(post.id)}/">${esc(post.title)}</a></h2><p>${esc(post.preview)}</p><span class="note">${esc(stockText)}</span><a class="text-link" href="/archive/${esc(post.id)}/">閱讀摘要 ↗</a></article>`;
}).join('');
write('archive/index.html', page('歷年文章摘要庫', '按股票、年份、月份或主題搜尋歷年港股與美股文章摘要。全文連往 Patreon，閱讀權限以原文為準。', '/archive/', `<div class="shell"><header class="page-intro"><p class="eyebrow">RESEARCH ARCHIVE</p><h1>歷年研究，有跡可尋。</h1><p>${posts.length} 篇公開摘要；全文連往 Patreon，閱讀權限以該篇文章為準。資料庫整理日期 ${esc(archive.generated_at.slice(0, 10))}。</p></header><div class="filter-bar" id="archive-filters"><label class="sr-only" for="archive-query">搜尋文章或股票</label><input type="search" id="archive-query" placeholder="搜尋文章、股票代號或公司名"><label class="sr-only" for="archive-category">文章分類</label><select id="archive-category"><option value="">全部分類</option>${Object.entries(archive.cat_labels).map(([id, name]) => `<option value="${esc(id)}">${esc(name)}</option>`).join('')}</select><label class="sr-only" for="archive-year">文章年份</label><select id="archive-year"><option value="">全部年份</option>${years.map(y => `<option>${y}</option>`).join('')}</select><label class="sr-only" for="archive-month">文章月份</label><select id="archive-month"><option value="">全部月份</option>${Array.from({ length: 12 }, (_, i) => `<option value="${String(i + 1).padStart(2, '0')}">${i + 1} 月</option>`).join('')}</select></div><p id="archive-count" class="directory-count" role="status">${posts.length} 篇摘要</p><div class="cards" id="archive-directory">${archiveCards}</div><div class="article-actions" id="archive-pagination" hidden><button class="button secondary" id="archive-prev" type="button">← 上一頁</button><button class="button secondary" id="archive-next" type="button">下一頁 →</button></div><section class="section" id="newsletter">${newsletter}</section></div>`));
console.log(`Built homepage, free tools, about, research directory, briefing and ${companies.length} complete company reports.`);
